# @package _group_
name: 'cora'
_target_: examples.datasets.cora.CoraDataset
params:
  defaulTasksMixin:
    - _target_: examples.tasks.classification.CategoricalClassificationStepsMixin
  num_edges: -1
  num_layers: ${model.params.num_layers}
  transform:
    - _target_: torch_geometric.transforms.NormalizeFeatures
  samplers:
    - stage: 'train'
      sampling: 'dataloader'
    - stage: 'val'
      sampling: 'dataloader'
    - stage: 'test'
      sampling: 'dataloader'
