# @package _group_
name: 'faust'
_target_: examples.datasets.faust.FAUSTDataset
params:
  pre_transform:
    - _target_: torch_geometric.transforms.FaceToEdge
    - _target_: torch_geometric.transforms.Constant
      params:
        value: 1
  train_transform:
    - _target_: torch_geometric.transforms.Cartesian
  test_transform:
    - _target_: torch_geometric.transforms.Cartesian
  samplers:
    - stage: 'train'
      sampling: 'dataloader'
    - stage: 'val'
      sampling: 'dataloader'
