# @package _group_
name: 'ppi'
_target_: examples.datasets.${dataset.name}.PPIDataset
params:
  defaulTasksMixin:
    - _target_: examples.tasks.classification.BinaryClassificationStepsMix
  num_layers: ${model.params.num_layers}
  transform:
    - activate: True
      _target_: torch_geometric.transforms.GCNNorm
    - activate: True
      _target_: torch_geometric.transforms.ToSparseTensor
  samplers:
    - stage: 'train'
      sampling: 'dataloader'
    - stage: 'val'
      sampling: 'dataloader'
    - stage: 'test'
      sampling: 'dataloader'
