# @package _group_
name: 'reddit'
_target_: examples.datasets.reddit.RedditDataset
params:
  defaulTasksMixin:
    - _target_: examples.tasks.classification.CategoricalStepsMixin
  num_edges: 25
  num_layers: ${model.params.num_layers}
  samplers:
    - stage: 'train'
      sampling: 'neighbor_sampler'
    - stage: 'val'
      sampling: 'dataloader'
    - stage: 'test'
      sampling: 'dataloader'
