# @package _group_
name: 'zinc'
_target_: examples.datasets.${dataset.name}.ZINCDataset
params:
  defaulTasksMixin:
    - _target_: examples.tasks.classification.CategoricalClassificationStepsMixin
  num_layers: ${model.params.num_layers}
  samplers:
    - stage: 'train'
      sampling: 'dataloader'
    - stage: 'val'
      sampling: 'dataloader'
    - stage: 'test'
      sampling: 'dataloader'
