# @package _group_
name: 'arma'
_target_: examples.models.${model.name}.ARMAConvNet
params:
  num_layers: 2
  hidden_channels: 16
  num_stacks: 3
  arma_num_layers: 2
  shared_weights: False
  dropout: 0.25
